import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Learning Nextjs </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={inter.className}>op Coder</h1>

        <Image
          src={'/shutterstock_173668979.jpg'}
          width={450}
          height={310}
          alt="img"
          className={styles.img}
        />
      </main>
    </>
  );
}
